version: '3'

services:
  auth:
    image: auth-app:v1
    container_name: auth-container
    network_mode: host
    restart: always

  funcapi:
    image: funcapi-app:v1
    container_name: funcapi-container
    network_mode: host
    restart: always

  ecoweb:
    image: ecoweb-app:v1
    container_name: ecoweb-container
    network_mode: host
    restart: always
