# 使用官方 Python 映像作為基礎映像
FROM python:3.9

# 安裝系統依賴 (包含 TA-Lib 開發套件)
RUN apt-get update && \
    apt-get install -y build-essential wget git && \
    wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz && \
    tar -xzvf ta-lib-0.4.0-src.tar.gz && \
    cd ta-lib && \
    ./configure --prefix=/usr && \
    make && make install && \
    cd .. && rm -rf ta-lib ta-lib-0.4.0-src.tar.gz

# 設定工作目錄
WORKDIR /app

# 複製 requirements.txt 並安裝 Python 依賴
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# 複製 ecoweb 和 config 目錄
COPY ecoweb/ ecoweb/
COPY config/ config/
COPY .env .env

# 設定工作目錄到 ecoweb
WORKDIR /app/ecoweb

# 開放應用程式運行的端口
EXPOSE 55555

# 啟動 Django 應用程式
CMD ["python", "manage.py", "runserver", "0.0.0.0:55555"]